---

# Ensure the CDN configurations
- name: "Install the official Red Hat GPG Key from the CDN"
  ansible.builtin.get_url:
    url: "https://www.redhat.com/security/data/fd431d51.txt"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    mode: "0600"

- name: "Install the official convert2rhel repo configuration from the CDN"
  ansible.builtin.get_url:
    url: "https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo"
    dest: "/etc/yum.repos.d/convert2rhel.repo"
    mode: "0600"
